### ISSUE TITLE
Creating Result.ok(null) results in NPE when calling result.unwrapOrElseThrow()

### ISSUE THREAD

**Issue by cypressf** [HubSpot/algebra#17]
Same with VoidResult.

I'm unwrapping a result, which is inside a generically typed method. If the type is a Void, which gets wrapped in a result and then extracted it'd be nice to extract the null right back out, instead of failing.

If it has to fail, I think it'd be better to fail early, inside Result.ok(null).

**Comment by mjball** [comment]
I think this the problem with https://github.com/HubSpot/algebra/pull/16 addresses already.

**Comment by cypressf** [comment]
Cool. Feel free to close this as a duplicate if that's the case.

**Comment by cypressf** [comment]
Oh, that's a PR! nice. I guess we can close this when the pr is merged

**Comment by stevegutz** [comment]
Fixed. You can now use `Result#nullOk` and `Result#nullErr` to pass null values (don't use `Void` or `null` directly!).
