### ISSUE TITLE
Comparing VoidResult.ok() Results in NPE

### ISSUE THREAD

**Issue by tpoll** [HubSpot/algebra#18]
The generated equals function looks like

```java
public boolean equals(Object obj) {
      return (obj instanceof VoidResult) && ((VoidResult<ERROR_TYPE>) obj).match((err) -> false,
          (ok) -> this.ok.equals(ok));
    }
```
we should try to override this to handle `null` better.

**Comment by tpoll** [comment]
@zklapow

**Comment by tpoll** [comment]
@lorcanthrope  I think it should.

**Comment by stevegutz** [comment]
Fixed. You can now use `Result#nullOk` and `Result#nullErr` to pass null values (don't use `Void` or `null` directly!).
